name: C/C++ CI

on: [push]

jobs:
  build:
    name: building
    runs-on: ubuntu-20.04
    container: heliconwave/rpi_ci:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: ls -ltrha; pwd
    #      run: mkdir build; cd build; -DCMAKE_TOOLCHAIN_FILE=/workspaces/rpi_crosscompile/rpitoolchain.cmake ..
