name: C/C++ CI

on: [push]

jobs:
  build:
    name: building
    runs-on: ubuntu-20.04
    container: heliconwave/rpi_devcontainer:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: CMake Configure
      run: mkdir build; cd build; cmake -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/rpitoolchain.cmake ..
    - name: CMake Build
      run: cd build; cmake --build .
